# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3074dd49ff6dcb7362d874c71a89b6e941759137ab9d814db23d493d218d00568abb2a381487d08b97da3766e6d5fa35abab0c3594013d6b2562259fc33e3a0f

test:
  secret_key_base: 96d7347e28999d7ed05512902457a8a259d2f471f7ad45946c382e8915809a71141824ea965ca330249e5152326be961ca990ee13abc87d0f64b6c59a667a346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
